coverage:
  status:
    project:
      default:
        target: 80%  # Minimum coverage target
        threshold: 5%  # Allow 5% variation
        if_ci_failed: error  # Fail if CI fails
        only_pulls: false  # Check all branches
    patch:
      default:
        target: 80%  # Minimum coverage target for patches
        threshold: 5%  # Allow 5% variation
        if_ci_failed: error  # Fail if CI fails
        only_pulls: true  # Only check pull requests

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Only comment if there are coverage changes

ignore:
  - "tests/*"  # Ignore test files
  - "**/__init__.py"  # Ignore __init__.py files
  - "**/migrations/*"  # Ignore migration files
  - "manage.py"  # Ignore manage.py
  - "**/settings/*"  # Ignore settings files
  - "**/urls.py"  # Ignore URL configuration files

github_checks:
  annotations: true  # Enable annotations in GitHub checks 